### PR TITLE
Proper icon install

### PR DESCRIPTION
**Pull request by hfiguiere**
app-info is never an install path.

### CODE REVIEW

**Comment by Heliozoa** [comment]
Hi,
I tried using the desktop file but it just opens and immediately closes the terminal. I don't think a desktop file makes sense for this project, since you're supposed to call it from a terminal with arguments.

I think I made the icons with the intent of displaying them at https://flathub.org/apps/details/fi.mooc.tmc.tmc-cli-rust, but I don't know if non-TUI CLI applications are displayed on flathub.

**Comment by hfiguiere** [comment]
Installing in `/app/share/app-info/` is WRONG. 

The desktop file is not meant to be used either, it's just the only way to declare the icon. It says `Terminal=true` so if the destkop environment ignores it, then the desktop environment is wrong.

**Comment by hfiguiere** [comment]
the flathub website (in its current version) will not display command line apps.

**Comment by Heliozoa** [comment]
I think it'd be confusing for the user to have a desktop entry that doesn't work and is not meant to be used. I'll just remove the icons for now since they're not being displayed anywhere, maybe they can be added back in later if flathub starts to display CLI apps.

**Pull request closed without merging**
